config/routes.rb
TocCalc::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/services"
  get "static_pages/tools"
  get "static_pages/contact_us"
  get "static_pages/papers"
  resources :projects do  
      resources :tasks
  end

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  validates :name,  :presence => true, :uniqueness => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, :presence => true
  validates :lower,  :presence => true, :numericality => {:greater_than => 0}
  validates :upper,  :presence => true, :numericality => {:greater_than_or_equal_to => :lower}
  belongs_to :projects
  has_many :subtasks, :class_name => "Task", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_task, :class_name => "Task", :foreign_key => "parent_id"
  
  after_validation :set_risk, on: [:create, :update]
  
  protected
  def set_risk
    self.error = ((self.upper-self.lower)/2)*((self.upper-self.lower)/2)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render action: 'index', status: :created, location: @project }
#TODO Not sure this json statement is correct - need to redirect to index.  What is 'location'?
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_url, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      # params[:project]
      params.require(:project).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def services
  end

  def tools
  end

  def contact_us
  end

  def papers
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /projects/#/tasks
  # GET /projects/#/tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /projects/#/tasks/1
  # GET /projects/#/tasks/1.json
  def show
  end

  # GET /projects/#/tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /projects/#/tasks/1/edit
  def edit
  end

  # POST /projects/#/tasks
  # POST /projects/#/tasks.json
  def create
    @task = @project.tasks.new(task_params)
    if @task.buffer == :false
      #:update_buffer
    end
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_tasks_path (@project), notice: 'Task was successfully created.' }
        format.json { render action: 'index', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/#/tasks/1
  # PATCH/PUT /projects/#/tasks/1.json
  def update
    if @task.buffer == false
      #:update_buffer
    end
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to [@project, @task], notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/#/tasks/1
  # DELETE /projects/#/tasks/1.json
  def destroy
    @task.destroy
    if @task.buffer == false
      :update_buffer
    end
    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project) }
      format.json { head :no_content }
    end
  end
  
  def update_buffer
    @grouped_tasks = Task.find_by :buffer => false, :parent_id => @task.parent_id
    @buffer_value = @grouped_tasks.sum(:error)
    #TODO If buffer exists, update the values
    if @buffer.exists?
      
    else
      Task.new(:name => 'Buffer', :Lower => @buffer_value, :upper => @buffer_value, :buffer => true)
      Task.save
    end
    #TODO If not, then create a buffer entry
    
    return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find(params[:id])
      @buffer = @project.tasks.find_by :buffer => true, :parent_id => @task.parent_id
    end
    
    def get_project
      @project = Project.find(params[:project_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :upper, :lower)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TocCalc</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="side_bar_top">
		</div>	
		<div class="side_bar">
		</div>
		<div class="header">
			<div class="logo">		
				<%= image_tag 'Master_PO4_Logo.png', size: '90x60', alt: 'PO4 Management' %>		
			</div>
		</div>
		<div class="menu_bar">
			<ul>
				<li><a href=/static_pages/home >Home</a></li>
				<li><a href=/static_pages/services >Services</a></li>
				<li><a href=/static_pages/tools >Tools</a></li>
				<li><a href=/static_pages/about >About</a></li>
				<li><a href=/static_pages/papers >Papers</a></li>
				<li><a href=/static_pages/contact_us >Contact Us</a></li>
			</ul>
		</div>
		<div class="main">
			<div class="display">
				<%= yield %>
			</div>
		</div>
	</div>
	<div class="footer">
			<p>&copy   PO4 Mangement Limited, 23 Selsey Avenue, Southsea HAMPSHIRE. PO4 9QL</p>
			<p>Company Registration Number: xxxxxxxx  ::  VAT: vvvvvvvvv</p>
	</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
	  <%= f.label :name %><br>
	  <%= f.text_field :name %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Balanced Risks - Projects</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Project Name</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
		<td><%= project.name %></td>
        <td><%= link_to 'Detail', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
		<td><%= link_to 'Show Tasks', project_tasks_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact_us.html.erb
<h1>StaticPages#contact_us</h1>
<p>Find me in app/views/static_pages/contact_us.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/static_pages/papers.html.erb
<h1>StaticPages#papers</h1>
<p>Find me in app/views/static_pages/papers.html.erb</p>

app/views/static_pages/services.html.erb
<h1>StaticPages#services</h1>
<p>Find me in app/views/static_pages/services.html.erb</p>

app/views/static_pages/tools.html.erb
<h1>Help is at Hand</h1>
<p>As much as we might like our customers to think we perform magic, we don't.  We do, however, know how to apply the tools of our trade.  But if we aspire to leave our customers better able to support themselves in the future, we need to share some of those tools.</p>
<p>Below is a collection of tools, offered without warrentee, but we hope will help in some small way.</p>
<p>Enjoy!</p>

<ul>
	<li><a href=#>Project Risk</a><p> - Estimating in projects is....</p><li>
	<li><a href=#>PairWise Comparisons</a><p> - Finding a balance between competing priorities is challenging: especially if the priorities cannot be quantified.  How do you compare 'staff moral' against 'reputation' or 'community standing'.</p><li>	
</ul>

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :lower %><br>
		<%= f.text_field :lower %>
	</p>
	<p>
		<%= f.label :upper %><br>
		<%= f.text_field :upper %>
	</p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', project_task_path(@project, @task) %> |
<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/index.html.erb
<h1>Balanced Risks - Tasks for:</h1>
<h2><%= @project.name %></h2>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Task Name</th>
      <th>Average Effort</th>
      <th>Worst Case</th>
	  <th>Risk Index</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
	<tr>
		<td><%= task.name %></td>
		<td><%= task.lower %></td>
		<td><%= task.upper %></td>
		<td><%= task.error %></td>
        <td><%= link_to 'Edit', edit_project_task_path(id: :task_id) %></td>
        <td><%= link_to 'Destroy', project_task_path(id: :task_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td><%= link_to 'Sub Task'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path %>
<%= link_to 'Back to Projects', projects_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@project) %>